### ISSUE TITLE
Monolog Error: Fatal error: Uncaught TypeError: Argument 2 passed to Monolog\Logger::info()

### ISSUE THREAD

**Issue by rclmclaney** [gabrielbull/omnimail#10]
I'm receiving the below error when trying to use Monolog whilst following your instructions, but replacing Mailgun with SendGrid. 

`Fatal error: Uncaught TypeError: Argument 2 passed to Monolog\Logger::info() must be of the type array, object given, called in /vendor/omnimail/omnimail/src/Sendgrid.php on line 94 and defined in vendor/monolog/monolog/src/Monolog/Logger.php:543 Stack trace: #0 /vendor/omnimail/omnimail/src/Sendgrid.php(94): Monolog\Logger->info('Email sent: 'Ne...', Object(Omnimail\Email)) #1/enquiry.php(47): Omnimail\Sendgrid->send(Object(Omnimail\Email)) #2 {main} thrown in /vendor/monolog/monolog/src/Monolog/Logger.php on line 543`

My code: 

```
$logger = new Logger('name');
$logger->pushHandler(new StreamHandler('errors.log', Logger::INFO));

$sender = new Sendgrid($apiKey, $logger);

$email = (new Email())
    ->addTo('sales@test.com')
    ->setFrom('noreply@test.com')
    ->setSubject('New Enquiry')
    ->setHtmlBody($emailHtml);

$sender->send($email);
```

I'm not sure if I'm missing something or if you have a quick fix for the issue in the Omnimail\Sendgrid class?

Thanks in advance!

**Comment by gabrielbull** [comment]
Hey thanks for reporting! I just publish a new release [0.1.4](https://github.com/gabrielbull/omnimail/releases/tag/0.1.4) with a fix for your issue. Let me know if you experience anymore problems.

**Comment by rclmclaney** [comment]
It works perfectly now, thank you for the quick fix and brilliant package!
