### ISSUE TITLE
Create method

### ISSUE THREAD

**Issue by jeremy-hunter** [gabrielbull/omnimail#14]

**Comment by gabrielbull** [comment]
Can you explain your issue?

**Comment by jeremy-hunter** [comment]
Whoops

Anyways...

Would you be opposed to a static create() method that took the service name and created the object for you? (Like omnipay) Just trying to avoid including a bunch of classes that are actually not needed just to use a switch to figure out which one I need for this particular instance.

**Comment by gabrielbull** [comment]
Something like this?

```php
Omnimail::create(Omnimail::SendGrid, $apiKey);
```

**Comment by eileenmcnaughton** [comment]
I think you would need to pass an array or interface rather than a single variable as it might vary

**Comment by gabrielbull** [comment]
So like this:

```php
Omnimail::create(Omnimail::SendGrid, [
    'apiKey' => $apiKey
]);
```

Anyone got time for this? Should be a simple implementation.

**Comment by gabrielbull** [comment]
Merged into develop branch.
