### ISSUE TITLE
Roadmap....

### ISSUE THREAD

**Issue by eileenmcnaughton** [gabrielbull/omnimail#15]
Hi,

I was looking for something like this that took an Omnipay-style approach to Mail integration & this looks good. The only thing is .. there is no actual overlap between what your package is doing & what I am working on - I'm going to paste it up here anyway in case there is some synergy - as I feel like you have the starting point for more comprehensive integration with mailing providers. 

The way I expect my calling code to look is something like
```
$mailingIntegration = new Omnimail::create('Silverpop', $credentials);
$mailings = $mailingIntegration->getMailings(array('start_date' => '2017-01-01'));

foreach ($mailings as $mailing) {
  $html = $mailing->getHtml();
  $subject = $mailing->getSubject();
  $text = $mailing->getText();
  // this is their unique ID
  $theirIdentifier = $mailing->getProviderIdentifier();

  $ourIdentifier = $mailing->getIndentifier();
  $name = $mailing->getName();
  $created_date = $mailing->getCreatedDate();
  $scheduled_date = $mailing->getScheduledDate();

  $numberSent = $mailing->getNumberSent();
  $numberDelivered = $mailing->getNumberDelivered();
    // e.g spam
  $numberBounced = $mailing->getNumberBounced();
  $numberBlocked = $mailing->getNumberBlocked();
  $numberUnsubscribe = $mailing->getNumberUnsubscribed();
  $numberComplaints = $mailing->getNumberAbuseReports();
  $numberOpens = $mailing->getNumberOpens();
  $numberUniqueOpens = $mailing->getNumberUniqueOpens();
  $numberClicks = $mailing->getNumberClicks();
  $numberUniqueClicks = $mailing->getNumberUniqueClicks();

  $bounces = $mailing->getBounces();
  foreach ($bounces as $bounce) {
    $recipient = $bounce->getRecipient();
    $ourIdentifier= $recipient->getIdentifier();
    // ie identifier for the provider
    $theirIdentifier = $recipient->getProviderIdentifier();
    $emailAddress = $recipient->getEmail();
    $bounceType = $bounce->getBounceType();
    
  }
}
```

**Comment by gabrielbull** [comment]
Hi @eileenmcnaughton,

Do you mean you'd like this project to have more features. From what I get from your posts, you'd like these features to include:

 - Mass mailings/Campaigns
 - The ability to schedule emails/campaigns
 - The ability to fetch sent emails/campaigns
 - The ability to see stats for those sent emails/campaigns

Am I missing something?

**Comment by eileenmcnaughton** [comment]
Yes, well, while I think the first 2 would be useful the second 2 are what I need. I'm going to be working on those features over the next couple of weeks, and would prefer to contribute to an existing project than start a new one - this seemed the closest to what I would do if doing it myself, but there may not be enough overlap?

**Comment by gabrielbull** [comment]
I think they would be nice features as well. Not all providers support these features so there would need to be some mechanism in place to warn users when using a feature not supported.

**Comment by gabrielbull** [comment]
I've moved stuff from this issue into separate issues:

 - #21 Add support for campaigns 
 - #22 Add support for scheduling emails and campaigns 
 - #23 Add support for fetching sent emails and campaigns 
 - #24 Add support for stats for sent emails and campaigns
