### ISSUE TITLE
Guzzle should be required directly

### ISSUE THREAD

**Issue by shadowhand** [gabrielbull/omnimail#4]
What is the benefit to requiring `php-http` via the Guzzle adapter over requiring Guzzle directly? Seems like it only adds more dependencies.

**Comment by bretto36** [comment]
Check out the php-http site - http://httplug.io/ 
Omnimail uses the guzzle adapter by default but you might want to use a different library for the http client protocol. You can by switching to a different adapter. 
There are a bunch of different versions here - https://github.com/php-http

**Comment by shadowhand** [comment]
@bretto36 in that case, `php-http/guzzle6-adapter` should be a suggestion instead of a dependency. I am very familiar with HTTPlug but the current usage offers no benefits.

**Comment by Nyholm** [comment]
May I suggest that we should be requiring [php-http/client-implementation](https://packagist.org/providers/php-http/client-implementation) instead and then use php-http/discovery to find the installed client. That would give the benefit that the end user can choose what library to use to send HTTP messages. That would remove all dependencies on Guzzle. 

I would be happy to assist with a PR if you want.

**Comment by gabrielbull** [comment]
@Nyholm That sounds like a good idea, do you have time for the PR?

**Comment by Nyholm** [comment]
Sure.  I'm on the way to the airport now. I might have time before I board the plane.

**Comment by gabrielbull** [comment]
PR has been merged. Thanks guys!
