### ISSUE TITLE
Backward Compatibility - Scalar type hinting is supported only from PHP >= 7.0

### ISSUE THREAD

**Issue by shahariaazam** [gabrielbull/omnimail#42]
Here is the constructor of `AmazonSES` from https://github.com/gabrielbull/omnimail/blob/master/src/AmazonSES.php#L137

```
public function __construct($accessKey = null, $secretKey = null, $host = self::AWS_US_EAST_1, $verifyPeer = true, $verifyHost = true, LoggerInterface $logger = null, string $signatureVersion = SimpleEmailService::REQUEST_SIGNATURE_V4)
{
    $this->verifyPeer = $verifyPeer;
    $this->verifyHost = $verifyHost;
    $this->accessKey = $accessKey;
    $this->secretKey = $secretKey;
    $this->host = $host;
    $this->logger = $logger;
    $this->signatureVersion = $signatureVersion;
}
```
In the last argument `string $signatureVersion = SimpleEmailService::REQUEST_SIGNATURE_V4`. Scalary type hinting on argument is not supported in PHP5.5 as this library is supposed to support PHP5.5 too.

It seems that in the recent PR https://github.com/gabrielbull/omnimail/pull/40 that changes were made. But it will break the backward compatibility for PHP5.5.

We should fix it ASAP.

**Comment by shahariaazam** [comment]
@stevecoug can you please fix this with a patch if you have time. Or, patch is welcome from anybody.

Thank you.

**Comment by stevecoug** [comment]
@shahariaazam can you review the PR and merge if it works for you?

**Comment by shahariaazam** [comment]
> can you review the PR

Yes, I just did.

Thanks and really appreciated your effort. :)

**Comment by shahariaazam** [comment]
> I could also copy the constant into Omnimail's AmazonSES

I think you don't need to remove constant. So its OK to keep `$signatureVersion = SimpleEmailService::REQUEST_SIGNATURE_V4`

**Comment by stevecoug** [comment]
Gotcha, sorry about the confusion, I wasn't thinking clearly obviously. It's been a while since I used PHP 5.

**Comment by shahariaazam** [comment]
Thanks @stevecoug for the PR. Appreciated 👍
