### ISSUE TITLE
Use php7 random_bytes

### ISSUE THREAD

**Issue by b1rdex** [gabrielbull/omnimail#8]
Ref: https://github.com/gabrielbull/omnimail/blob/1831ecdd6577eeb4cac505ee20e57944fe68c2e1/src/Utils/Token.php#L61

Use https://github.com/paragonie/random_compat

**Comment by gabrielbull** [comment]
Will do soon, thanks for pointing it out!

**Comment by gabrielbull** [comment]
Done! Thanks! 🎊🍾
